# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "usbhid"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d1c591e6-0b3e-47cb-a166-986436ec22be";
    fsType = "ext4";
    options = ["nofail" "x-systemd.device-timeout=1s"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/7329-41C8";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077" "nofail" "x-systemd.device-timeout=1s"];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
